name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # 这个新步骤添加了你的服务器到 known_hosts 以避免 Host key verification failed 的问题
    - name: Add server to known hosts
      run: |
        echo "dragonballchih.top $(ssh-keyscan dragonballchih.top)" >> ~/.ssh/known_hosts
      
    - name: Deploy to server
      run: |
        ssh lighthouse@dragonballchih.top 'cd /var/www/koaapp && git pull origin main && /home/lighthouse/.nvm/versions/node/v18.17.1/bin/npm install && /home/lighthouse/.nvm/versions/node/v18.17.1/bin/npm run build'

