name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      
    - name: Deploy to server
      run: |
        ssh lighthouse@dragonballchih.top && export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh 'cd /var/www/koaapp && git pull origin main && npm install && npm run build'

